- id: '1592424546560'
  alias: Aquarium temperature too warm
  description: ''
  trigger:
  - above: 79
    device_id: 0cdc7f84dfc845c4a180eb5c25035128
    domain: sensor
    entity_id: sensor.aquarium_temperature
    platform: device
    type: value
  condition: []
  action:
  - data:
      message: The aquarium temperature is too warm
    service: hangouts.send_message
