homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 441
  # metric for Metric, imperial for Imperial
  unit_system: Imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: !secret configurator_url
  terminal:
    title: Terminal
    icon: mdi:console-line
    url: !secret terminal_url
  octopi:
    title: Octopi
    url: !secret octopi_url

# Enables configuration UI
config:

lovelace:
  mode: yaml

influxdb:
  username: !secret influx_user
  password: !secret influx_pass

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  base_url: !secret base_url
  api_password: !secret http_password
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

mqtt:
  broker: localhost

# Sensors
sensor:
  - platform: darksky
    api_key: !secret darksky_api
    monitored_conditions:
      - summary
      - temperature
      - precip_type
      - precip_probability
      - precip_accumulation
      - wind_speed
      - humidity
      
  - platform: hue
  - platform: template
    sensors:
      living_room_lux:
        friendly_name: 'Living Room Light Level'
        value_template: '{{states.sensor.living_room_motion_motion_sensor.attributes.lx}}'
        unit_of_measurement: lux
        
      living_room_battery:
        friendly_name: 'Living Room Motion Sensor Battery'
        value_template: '{{states.sensor.living_room_motion_motion_sensor.attributes.battery}}'
#        unit_of_measurement: percent
        
#      living_room_motion_temp:
#        friendly_name: 'Living Room Motion Sensor Temp'
#        value_template: '{{states.sensor.living_room_motion_motion_sensor.attributes.temperature}}'
#        unit_of_measurement: °C
        
      kitchen_lux:
        friendly_name: 'Kitchen Light Level'
        value_template: '{{states.sensor.kitchen_motion_motion_sensor.attributes.lx}}'
        unit_of_measurement: lux
        
      kitchen_battery:
        friendly_name: 'Kitchen Motion Sensor Battery'
        value_template: '{{states.sensor.kitchen_motion_motion_sensor.attributes.battery}}'
#        unit_of_measurement: percent
        
#      kitchen_motion_temp:
#        friendly_name: 'Kitchen Motion Sensor Temp'
#        value_template: '{{states.sensor.kitchen_motion_motion_sensor.attributes.temperature}}'
#        unit_of_measurement: °C
        
      hallway_lux:
        friendly_name: 'Hallway Light Level'
        value_template: '{{states.sensor.hallway_motion_motion_sensor.attributes.lx}}'
        unit_of_measurement: lux
        
      hallway_battery:
        friendly_name: 'Hallway Motion Sensor Battery'
        value_template: '{{states.sensor.hallway_motion_motion_sensor.attributes.battery}}'
#        unit_of_measurement: percent
        
#      hallway_motion_temp:
#        friendly_name: 'Hallway Motion Sensor Temp'
#        value_template: '{{states.sensor.hallway_motion_motion_sensor.attributes.temperature}}'
#        unit_of_measurement: °C

  - platform: mqtt
    name: "Basement Stairs Motion"
    command_topic: "smartthings/Basement Stairs/motion/cmd"
    state_topic: "smartthings/Basement Stairs/motion/state"
    qos: 1
    payload_on: "active"
    payload_off: "inactive"
    icon: mdi:run-fast

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

  
ecobee:
  api_key: !secret ecobee_api
  
device_tracker:
  - platform: unifi
    host: 10.1.1.22
    username: !secret unifi_user
    password: !secret unifi_password
    interval_seconds: 10
    consider_home: 60
    verify_ssl: false
    new_device_defaults:
      track_new_devices: False
      
  - platform: hue

media_player:
  - platform: plex

  - platform: spotify
    client_id: !secret spotify_client_id
    client_secret: !secret spotify_client_secret
  
  - platform: kodi
    host: 10.1.1.125

  - platform: denonavr
    host: 10.1.50.9
    name: Denon AVR
    
hue:
  bridges:
    - host:  10.1.70.17
      allow_hue_groups: false
      allow_unreachable: true

remote:
  - platform: harmony
    name: Living Room
    host: 10.1.70.11
    
camera:
  - platform: mjpeg
    name: 3D Printer
    mjpeg_url: http://10.1.50.35/webcam/?action=stream


google_assistant:
  project_id: !secret gass_project_id
  api_key: !secret gass_api
  exposed_domains:
    - switch
    - light
    - group
    - media_player
    - climate
    
switch:
  - platform: mqtt
    name: "Octopi"
    command_topic: "cmnd/octopi/power"
    state_topic: "stat/octopi/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    
octoprint:
    host: 10.1.50.35
    api_key: !secret octoprint_api
    bed: true
    number_of_tools: 2
    sensors:
      monitored_conditions:
        - 'Current State'
        - 'Temperatures'
        - 'Job Percentage'
        - 'Time Elapsed'
        - 'Time Remaining'
   
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml