title: Home Assistant
resources:
  - url: /local/mini-media-player-bundle.js?v=0.9.8
    type: module
  - url: /local/mini-graph-card-bundle.js?v=0.1.0
    type: module
  - url: /local/simple-thermostat.min.js?v=1
    type: module
views:
  - badges: null
    cards:
      - entities:
          - device_tracker.eric
        show_header_toggle: false
        title: Presence
        type: entities
      - entities:
          - entity: group.all_lights
            icon: 'mdi:lightbulb'
            name: All
          - entity: group.main_floor_lights
            icon: 'mdi:lightbulb'
            name: Main Floor
          - entity: group.all_basement_lights
            icon: 'mdi:lightbulb'
            name: Basement
          - entity: group.master_bed_lights
            icon: 'mdi:lightbulb'
            name: Master Bed
        show_name: true
        show_state: true
        title: All Lights
        type: glance
      - entity: group.all_lights
        hold_action:
          action: none
        icon: 'mdi:lightbulb'
        name: Turn Off All Lights
        tap_action:
          action: call-service
          service: light.turn_off
        type: entity-button
      - entities:
          - entity: sun.sun
          - entity: sensor.dark_sky_summary
            name: Summary
          - entity: sensor.dark_sky_temperature
          - entity: sensor.dark_sky_humidity
          - entity: sensor.dark_sky_wind_speed
          - entity: sensor.dark_sky_precip
          - entity: sensor.dark_sky_precip_probability
        title: Current Weather
        type: glance
      - entity: weather.thermostat
        name: Weather Forecast
        type: weather-forecast
      - type: custom:simple-thermostat
        entity: climate.thermostat
        step_size: 1
        sensors:
           - attribute: actual_humidity
             name: Humidity
           - attribute: climate_mode
             name: Mode
           - attribute: fan
             name: Fan
        hide:
           mode: true
           state: true
      - entity: media_player.spotify
        type: custom:mini-media-player
        artwork_border: true
        artwork: cover
        show_source: true
    path: default_view
    title: Home
  - badges: []
    cards:
      - entities:
          - entity: sensor.kitchen_temperature
            name: Temp
          - entity: sensor.kitchen_motion_motion_sensor
            name: Kitchen
          - entity: sensor.kitchen_lux
            name: Light
          - entity: sensor.kitchen_battery
            icon: 'mdi:battery'
            name: Battery
          - entity: binary_sensor.kitchen_occupancy
            name: Occupancy
        title: Kitchen Sensors
        type: glance
      - entities:
          - group.front_entry_lights
          - group.stairs_lights
          - group.dining_room_lights
          - group.kitchen_lights
        show_header_toggle: true
        title: Main Floor Lights
        type: entities
      - entities:
          - light.dining_front_left
          - light.dining_front_right
          - light.dining_rear_left
          - light.dining_rear_right
        show_header_toggle: true
        title: Dining Room
        type: entities
      - entities:
          - light.kitchen_fridge
          - light.kitchen_front_middle
          - light.kitchen_sink
          - light.kitchen_garage_door
        show_header_toggle: true
        title: Kitchen Lights
        type: entities
      - entities:
          - light.stairs
        show_header_toggle: true
        title: Stairs
        type: entities
      - entities:
          - light.front_entry
        show_header_toggle: true
        title: Front Entry
        type: entities
    path: main_floor
    title: Main Floor
  - badges: []
    cards:
      - entities:
          - entity: sensor.living_room_temperature
            name: Temp
          - entity: sensor.living_room_motion_motion_sensor
            name: Living Room
          - entity: sensor.living_room_lux
            name: Light
          - entity: sensor.living_room_battery
            icon: 'mdi:battery'
            name: Battery
          - entity: sensor.basement_stairs_motion
            name: Stairs
          - entity: binary_sensor.living_room_occupancy
            name: Occupancy
        title: Living Room Sensors
        type: glance
      - entity: group.all_basement_lights
        hold_action:
          action: more-info
        tap_action:
          action: toggle
        type: entity-button
      - entities:
          - entity: group.living_room_lamps
          - entity: group.living_room_ceiling_all_lights
            name: All Ceiling
          - entity: group.living_room_ceiling_color_lights
          - entity: group.living_room_ceiling_rear_lights
        show_header_toggle: true
        title: Living Room Lights
        type: entities
      - entities:
          - light.corner_lamp
          - light.couch_table_lamp
          - light.loveseat_table_lamp
          - light.square_lamp
        show_header_toggle: true
        title: Living Room Lamps
        type: entities
      - entity: media_player.denon_avr
        type: media-control
      - entity: media_player.kodi
        type: media-control
      - entities:
          - light.hue_ambiance_downlight_1
          - light.hue_ambiance_downlight_2
          - light.hue_color_downlight_1
          - light.hue_color_downlight_2
          - light.hue_color_downlight_3
          - light.hue_color_downlight_4
        show_header_toggle: true
        title: Ceiling
        type: entities
      - entities:
          - remote.living_room
        show_header_toggle: false
        title: Remote
        type: entities
      - entity: media_player.spotify
        type: media-control
    path: basement
    title: Basement
  - badges: []
    cards:
      - entities:
          - entity: sensor.thermostat_temperature
            name: Temperature
          - entity: sensor.thermostat_humidity
            name: Humidity
          - entity: sensor.hallway_motion_motion_sensor
            name: Motion
          - entity: sensor.hallway_lux
            name: Light
          - entity: sensor.hallway_battery
            icon: 'mdi:battery'
            name: Battery
        title: Hallway Sensors
        type: glance
      - entities:
          - entity: binary_sensor.master_bedroom_occupancy
            name: Occupancy
          - entity: sensor.master_bedroom_temperature
            name: Temp
          - entity: light.hue_ambiance_lamp_1
        title: Master Bedroom Sensors
        type: glance
      - entities:
          - entity: light.hue_ambiance_lamp_1
        show_header_toggle: true
        title: Master Bedroom Lights
        type: entities
    path: upstairs
    title: Upstairs
  - badges: []
    cards:
      - type: horizontal-stack
        cards:
        - type: custom:mini-graph-card
          entity: sensor.dark_sky_temperature
          name: Outside Temp
          line_color: '#3498db'
          line_width: 2
          detail: 2
      - type: horizontal-stack
        cards:
        - type: custom:mini-graph-card
          entity: sensor.dark_sky_humidity
          name: Humidity
          line_color: '#e74c3c'
          line_width: 8
          detail: 2
        - type: custom:mini-graph-card
          entity: sensor.dark_sky_wind_speed
          name: Wind
          line_width: 8
          detail: 2
      - type: horizontal-stack
        cards:
        - type: custom:mini-graph-card
          entity: sensor.kitchen_temperature
          name: Kitchen
          line_color: '#3498db'
          line_width: 8
          detail: 2          
        - type: custom:mini-graph-card
          entity: sensor.living_room_temperature
          name: Living Room
          line_color: '#e74c3c'
          line_width: 8
          detail: 2          
        - type: custom:mini-graph-card
          entity: sensor.master_bedroom_temperature
          name: Master
          line_width: 8
          detail: 2          
      - type: horizontal-stack
        cards:
        - type: custom:mini-graph-card
          entity: sensor.thermostat_temperature
          name: Thermostat
          line_color: '#3498db'
          line_width: 8
          detail: 2          
        - type: custom:mini-graph-card
          entity: sensor.thermostat_humidity
          name: Thermostat Humidity
          line_color: '#e74c3c'
          line_width: 8
          detail: 2
      - hold_action:
          action: none
        image: >-
          https://radblast.wunderground.com/cgi-bin/radar/WUNIDS_map?station=FSD&brand=wui&num=1&delay=15&type=N0R&frame=0&scale=1.000&noclutter=0&showstorms=0&mapx=400&mapy=240&centerx=400&centery=240&transx=0&transy=0&showlabels=1&severe=0&rainsnow=1&lightning=0&smooth=0&rand=25809181&lat=0&lon=0&label=you
        tap_action:
          action: none
        type: picture
    title: Climate
  - badges: []
    cards:
      - entities:
          - entity: light.office_lamp
        show_header_toggle: false
        title: Office Lights
        type: entities
    title: Office
  - badges: []
    cards:
      - entities:
          - entity: switch.octopi
            icon: 'mdi:pi-box'
          - entity: sensor.octoprint_current_state
            name: Status
          - entity: sensor.octoprint_job_percentage
            name: Print %
          - entity: sensor.octoprint_target_tool0_temp
            name: Extruder
          - entity: sensor.octoprint_actual_bed_temp
            name: Bed
        title: 3D Printer Status
        type: glance
      - entity: camera.3d_printer
        type: picture-entity
    icon: ''
    title: 3D Printer