title: Home Assistant
resources:
  - url: /local/mini-media-player-bundle.js?v=0.9.8
    type: module
  - url: /local/mini-graph-card-bundle.js?v=0.1.0
    type: module
  - url: /local/simple-thermostat.min.js?v=1
    type: module
  - url: /local/lovelace-battery-entity/battery-entity.js?v=1
    type: module
views:
  - badges: null
    cards:
      - entities:
          - entity: device_tracker.eric
            name: Eric
        show_header_toggle: false
        title: Presence
        aspect_ratio: 866x356       
        state_image:
          "home": /local/house_home.jpg
          "away": /local/house_away.jpg  
        entity: device_tracker.eric_s_oneplus_7_pro
        type: picture-entity
        
      - entities:
          - entity: group.living_room_lamps
            icon: 'mdi:lightbulb'
            name: Living Room Lamps
          - entity: group.kitchen_lights
            icon: 'mdi:lightbulb'
            name: Kitchen
          - entity: light.kitchen_cabinets
            icon: 'mdi:lightbulb'
            name: Kitchen Cabinets
          - entity: light.kitchen_stairs
            icon: 'mdi:lightbulb'
            name: Kitchen Stairs
          - entity: group.dining_room_lights
            icon: 'mdi:lightbulb'
            name: Dining Room
          - entity: group.living_room_ceiling_all_lights
            icon: 'mdi:lightbulb'
            name: Basement Ceiling
          - entity: group.master_bed_lights
            icon: 'mdi:lightbulb'
            name: Master Bed
          - entity: light.office_lamp
            icon: 'mdi:lightbulb'
            name: Master Bed
        show_name: true
        show_state: true        
        title: All Lights 
        aspect_ratio: 866x356        
        state_image: 
          "on": /local/xx_l1_lightbulbs_main_on_cropped.jpg
          "off": /local/xx_l1_lightbulbs_main_off_cropped.jpg
        entity: group.lights_all
        type: picture-glance
        
      - entities:
          - entity: group.kitchen_lights
            name: Kitchen Lights
        title: Kitchen Lights
        aspect_ratio: 866x356
        state_image: 
          "on": /local/kitchen_lights_on_cropped.jpg
          "off": /local/kitchen_lights_off_cropped.jpg 
        entity: group.kitchen_lights
        type: picture-glance
 
      - entities:
          - entity: group.dining_room_lights
            name: Dining Room Lights
        title: Dining Room Lights
        aspect_ratio: 866x356
        state_image: 
          "on": /local/dining_lights_on_cropped.jpg
          "off": /local/dining_lights_off_cropped.jpg 
        entity: group.dining_room_lights
        type: picture-glance
        
      - entities:
          - entity: group.master_bed_lights
            name: Master Bedroom Lights
        title: Master Bedroom Lights
        aspect_ratio: 866x356        
        state_image: 
          "on": /local/master_lights_on_cropped.jpg
          "off": /local/master_lights_off_cropped.jpg 
        entity: group.master_bed_lights
        type: picture-glance
        
      - entities:
          - entity: group.all_living_room_lights
            name: Living Room Lights
        title: Living Room Lights
        aspect_ratio: 866x356        
        state_image: 
          "on": /local/living_room_lights_on_cropped.jpg
          "off": /local/living_room_lights_off_cropped.jpg 
        entity: group.all_living_room_lights
        type: picture-glance
 
      - entity: group.lights_all
        hold_action:
          action: none
        icon: 'mdi:lightbulb'
        name: Turn Off All Lights
        tap_action:
          action: call-service
          service: light.turn_off
        type: entity-button
      - entities:
          - entity: sun.sun
          - entity: sensor.dark_sky_summary
            name: Summary
          - entity: sensor.dark_sky_temperature
          - entity: sensor.dark_sky_apparent_temperature
            name: Feels Like
          - entity: sensor.dark_sky_humidity
          - entity: sensor.dark_sky_wind_speed
          - entity: sensor.dark_sky_precip
          - entity: sensor.dark_sky_precip_probability
        title: Current Weather
        type: glance  
      - entity: weather.thermostat
        name: Weather Forecast
        type: weather-forecast
      - type: thermostat
        entity: climate.thermostat
        step_size: 1
        sensors:
           - attribute: actual_humidity
             name: Humidity
           - attribute: climate_mode
             name: Mode
           - attribute: fan
             name: Fan
        hide:
           mode: true
           state: true
      - entity: media_player.spotify
        type: custom:mini-media-player
        artwork_border: true
        artwork: cover
        show_source: true
    path: default_view
    title: Home
  - badges: []
    cards:
      - entities:
          - entity: sensor.kitchen_temperature
            name: Temp
          - entity: binary_sensor.kitchen_motion_sensor_motion
            name: Kitchen
          - entity: sensor.kitchen_motion_sensor_light_level
            name: Light
#          - entity: sensor.kitchen_battery
#            icon: 'mdi:battery'
#            name: Battery
          - entity: binary_sensor.kitchen_occupancy
            name: Occupancy
        title: Kitchen Sensors
        type: glance
      - entities:
          - group.front_entry_lights
          - group.stairs_lights
          - group.dining_room_lights
          - group.kitchen_lights
        show_header_toggle: true
        title: Main Floor Lights
        type: entities
      - entities:
          - light.dining_front_left
          - light.dining_front_right
          - light.hue_color_downlight_3
          - light.hue_color_downlight_1
        show_header_toggle: true
        title: Dining Room
        type: entities
      - entities:
          - light.hue_color_downlight_4
          - light.kitchen_front_middle
          - light.hue_color_downlight_2
          - light.kitchen_garage_door
          - light.kitchen_cabinets
          - light.kitchen_stairs
        show_header_toggle: true
        title: Kitchen Lights
        type: entities
      - entities:
          - light.stairs
        show_header_toggle: true
        title: Stairs
        type: entities
      - entities:
          - light.front_entry
        show_header_toggle: true
        title: Front Entry
        type: entities
    path: main_floor
    title: Main Floor
  - badges: []
    cards:
      - entities:
          - entity: sensor.living_room_temperature
            name: Temp
          - entity: sensor.basement_stairs_motion
            name: Stairs
          - entity: binary_sensor.living_room_occupancy
            name: Occupancy
        title: Living Room Sensors
        type: glance
      - entity: group.all_basement_lights
        hold_action:
          action: more-info
        tap_action:
          action: toggle
        type: entity-button
      - entities:
          - entity: group.living_room_lamps
          - entity: group.living_room_ceiling_all_lights
            name: All Ceiling
          - entity: group.living_room_ceiling_rear_lights
        show_header_toggle: true
        title: Living Room Lights
        type: entities
      - entities:
          - light.corner_lamp
          - light.couch_table_lamp
          - light.loveseat_table_lamp
          - light.square_lamp
        show_header_toggle: true
        title: Living Room Lamps
        type: entities
      - entity: media_player.denon_avr
        type: custom:mini-media-player
        artwork_border: true
        artwork: cover
        show_source: true
      - entities:
          - entity: remote.living_room
        type: entities
      - entity: media_player.shield
        type: custom:mini-media-player
        artwork_border: true
        artwork: cover
        show_source: true
      - entities:
          - light.hue_ambiance_downlight_1
          - light.hue_ambiance_downlight_2
          - light.dining_rear_right
          - light.kitchen_sink
          - light.dining_rear_left
          - light.kitchen_fridge
        show_header_toggle: true
        title: Ceiling
        type: entities
      - entity: media_player.spotify
        type: custom:mini-media-player
        artwork_border: true
        artwork: cover
        show_source: true
      - entities:
          - entity: switch.christmas_tree
            icon: 'mdi:pine-tree'
            name: Tree
        show_header_toggle: false    
        title: Christmas Lights
        type: entities        
    path: basement
    title: Basement
  - badges: []
    cards:
      - entities:
          - entity: sensor.thermostat_temperature
            name: Temperature
          - entity: sensor.thermostat_humidity
            name: Humidity
          - entity: binary_sensor.hallway_motion_sensor_motion
            name: Motion
          - entity: sensor.hallway_motion_sensor_light_level
            name: Light
#          - entity: sensor.hallway_battery
#            icon: 'mdi:battery'
#            name: Battery
        title: Hallway Sensors
        type: glance
      - entities:
          - entity: binary_sensor.master_bedroom_occupancy
            name: Occupancy
          - entity: sensor.master_bedroom_temperature
            name: Temp
          - entity: light.hue_ambiance_lamp_1
        title: Master Bedroom Sensors
        type: glance
      - entities:
          - entity: light.hue_ambiance_lamp_1
        show_header_toggle: true
        title: Master Bedroom Lights
        type: entities
    path: upstairs
    title: Upstairs
  - badges: []
    cards:
      - type: horizontal-stack
        cards:
        - type: custom:mini-graph-card
          entity: sensor.dark_sky_temperature
          name: Outside Temp
          line_color: '#3498db'
          line_width: 4
          detail: 2
          hours_to_show: 24
        - type: custom:mini-graph-card
          entity: sensor.dark_sky_apparent_temperature
          name: Feels Like
          line_color: '#3498db'
          line_width: 4
          detail: 2
          hours_to_show: 24
      - type: horizontal-stack
        cards:
        - type: custom:mini-graph-card
          entity: sensor.dark_sky_humidity
          name: Humidity
          line_color: '#e74c3c'
          line_width: 4
          detail: 2
          hours_to_show: 24
        - type: custom:mini-graph-card
          entity: sensor.dark_sky_wind_speed
          name: Wind
          line_width: 4
          detail: 2
          hours_to_show: 24
      - type: horizontal-stack
        cards:
        - type: custom:mini-graph-card
          entity: sensor.kitchen_temperature
          name: Kitchen
          line_color: '#3498db'
          line_width: 4
          detail: 2
          hours_to_show: 24
        - type: custom:mini-graph-card
          entity: sensor.living_room_temperature
          name: Living Room
          line_color: '#3498db'
          line_width: 4
          detail: 2
          hours_to_show: 24
        - type: custom:mini-graph-card
          entity: sensor.master_bedroom_temperature
          name: Master
          line_color: '#3498db'
          line_width: 4
          detail: 2
          hours_to_show: 24
      - type: horizontal-stack
        cards:
        - type: custom:mini-graph-card
          entity: sensor.sn2_temperature 
          name: Server Rack
          line_color: '#3498db'
          line_width: 4
          detail: 2      
        - type: custom:mini-graph-card
          entity: sensor.thermostat_temperature
          name: Thermostat
          line_color: '#3498db'
          line_width: 4
          detail: 2   
        - type: custom:mini-graph-card
          entity: sensor.office_motion_sensor_temperature
          name: Office
          line_color: '#3498db'
          line_width: 4
          detail: 2
          hours_to_show: 24
      - hold_action:
          action: none
        image: >-
          https://radblast.wunderground.com/cgi-bin/radar/WUNIDS_map?station=FSD&brand=wui&num=1&delay=15&type=N0R&frame=0&scale=1.000&noclutter=0&showstorms=0&mapx=400&mapy=240&centerx=400&centery=240&transx=0&transy=0&showlabels=1&severe=0&rainsnow=1&lightning=0&smooth=0&rand=25809181&lat=0&lon=0&label=you
        tap_action:
          action: none
        type: picture
    title: Climate
  - badges: []
    cards:
      - entities:
          - entity: light.office_lamp
        show_header_toggle: false
        title: Office Lights
        type: entities
      - entities:  
          - entity: binary_sensor.office_motion_sensor_motion
            name: Motion
          - entity: sensor.office_motion_sensor_light_level
            name: Light
          - entity: sensor.office_motion_sensor_temperature
            name: Temperature
        type: glance
    title: Office
  - badges: []
    cards:
      - entities:
          - entity: sensor.sn2_temperature 
            name: Temperature
          - entity: sensor.sn2_humidity 
            name: Humidity
          - entity: sensor.sn2_pir
            name: Motion
          - entity: light.sn2_led
            name: Motion LED
        title: Server Rack Environment
        type: glance
#      - entities:    
#          - entity: sensor.server_rack_power
#            name: Power
#          - entity: sensor.server_rack_current
#            name: Current
#          - entity: sensor.server_rack_voltage
#            name: Voltage
#          - entity: sensor.server_rack_energy_today
#            name: Energy Today
#          - entity: sensor.server_rack_energy_yesterday
#            name: Energy Yesterday
#          - entity: sensor.server_rack_energy_total
#            name: Energy Total
#        title: Server Rack Energy Monitoring
#        type: glance
#      - entities:    
#          - entity: sensor.server_rack_heater_power
#            name: Power
#          - entity: sensor.server_rack_heater_current
#            name: Current
#          - entity: sensor.server_rack_heater_voltage
#            name: Voltage
#          - entity: sensor.server_rack_heater_energy_today
#            name: Energy Today
#          - entity: sensor.server_rack_heater_energy_yesterday
#            name: Energy Yesterday
#          - entity: sensor.server_rack_heater_energy_total
#            name: Energy Total
#        title: Server Rack Heater Energy Monitoring
#        type: glance
    title: Garage
  - badges: []
    cards:
      - entities:
          - entity: switch.heater_aux_pump
            name: Heater Auxilary Pump
        title: Heater
        type: entities
      - entities:    
          - entity: sensor.heater_aux_pump_power
            name: Power
          - entity: sensor.heater_aux_pump_current
            name: Current
          - entity: sensor.heater_aux_pump_voltage
            name: Voltage
          - entity: sensor.heater_aux_pump_energy_today
            name: Energy Today
          - entity: sensor.heater_aux_pump_energy_yesterday
            name: Energy Yesterday
          - entity: sensor.heater_aux_pump_energy_total
            name: Energy Total
        title: Energy Monitoring
        type: glance
    title: Utilities
  - badges: []
    cards:
      - entities:
          - entity: switch.octopi
            icon: 'mdi:pi-box'
          - entity: switch.3d_printer
            icon: 'mdi:printer-3d'
            name: Power
          - entity: sensor.octoprint_current_state
            name: Status
          - entity: sensor.octoprint_job_percentage
            name: Print %
          - entity: sensor.octoprint_target_tool0_temp
            name: Extruder
          - entity: sensor.octoprint_actual_bed_temp
            name: Bed
        title: 3D Printer Status
        type: glance
      - entities:    
          - entity: sensor.3d_printer_power
            name: Power
          - entity: sensor.3d_printer_current
            name: Current
          - entity: sensor.3d_printer_voltage
            name: Voltage
          - entity: sensor.3d_printer_energy_today
            name: Energy Today
          - entity: sensor.3d_printer_energy_yesterday
            name: Energy Yesterday
          - entity: sensor.3d_printer_energy_total
            name: Energy Total
        title: Energy Monitoring
        type: glance
      - entity: camera.3d_printer
        type: picture-entity
    icon: ''
    title: 3D Printer
    
  - badges: []
    cards:
      - entity: camera.front_door
        show_info: true
        type: picture-entity
      - entity: camera.backyard_garage
        show_info: true
        type: picture-entity
      - entity: camera.driveway
        show_info: true
        type: picture-entity
      - entity: camera.backyard_deck
        show_info: true
        type: picture-entity
      - entity: camera.garage
        show_info: true
        type: picture-entity

    title: Cameras